name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
          mkdir -p ~/app'
        rsync -avz --exclude=".git" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/app/

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
          cd ~/app &&
          docker-compose down &&
          docker-compose pull &&
          docker-compose up -d --build
        '
